version: "3.3"
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  userauthenticationservice:
    container_name: user-authentication-service
    build: UserAuthenticationService/
    hostname: localhost
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
    restart: always

  userproductservice:
    container_name: user-product-service
    build: UserProductService/
    hostname: localhost
    network_mode: host
    ports:
      - 8081:8081
    depends_on:
      - mongodbservice
    restart: always